### ISSUE TITLE
Are you guys thinking about React.js?

### ISSUE THREAD

**Issue by aimonext** [mostafizurhimself/admintoolkit-html#174]
We appreciate your work on Oss. We will love to know if you guys are working on the same dashboard to build it in React.js

**Comment by mostafizurhimself** [comment]
@aimonext Yes, we are working on React version too. Development Preview: https://react.getadmintoolkit.com/

**Comment by aimonext** [comment]
isn't it open source?

**Comment by mostafizurhimself** [comment]
@aimonext currently the react version is in development stage and it's not open source now.
